# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Gazettes South Africa
email: gazettes@code4sa.org
url: http://opengazettes.org.za
baseurl: 
description: Making South African Government Gazettes freely available.
twitter:
  username: code4sa
logo: /img/logo.png

gems:
  - jekyll-seo-tag

collections:
  gazettes:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/banner_5.png

# Build settings
markdown: kramdown
exclude: [vendor]
